# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16YM8qKuyBDtiQijv5459qPEcMCeEYaTz
"""

!pip install streamlit

import streamlit as st

st.write("Hello World")